#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 28 09:51:53 CET 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_CPU_Bootloader_behav -key {Behavioral:sim_1:Functional:tb_CPU_Bootloader} -tclbatch tb_CPU_Bootloader.tcl -view /net/netud/e/nhitar/Bureau/Conception_CPU/mini-cpu-students/mini-cpu/VIVADO/tb_CPU_Bootloader_behav.wcfg -log simulate.log"
xsim tb_CPU_Bootloader_behav -key {Behavioral:sim_1:Functional:tb_CPU_Bootloader} -tclbatch tb_CPU_Bootloader.tcl -view /net/netud/e/nhitar/Bureau/Conception_CPU/mini-cpu-students/mini-cpu/VIVADO/tb_CPU_Bootloader_behav.wcfg -log simulate.log

